#!/bin/sh

# if you're watching from your router, exclude its traffic from capture
router=10.1.1.1
# capture a traffic from/to a specific mac
client_mac=10:11:12:13:14:15

tcpdump -lpnni br-lan -s 200 ether host $client_mac and tcp and not host $router | ./sack
